### ISSUE TITLE
Let's make UPDATE /  INSERT work without pointers

### ISSUE THREAD

**Issue by martinrode** [programmfabrik/sqlpro#2] opened 2019-11-01 09:52 UTC
* Change TestInterfaceSliceSave like and fix the code so that this passes:

```
diff --git a/query_test.go b/query_test.go
index 6ac7631..68275d3 100644
--- a/query_test.go
+++ b/query_test.go
@@ -542,7 +542,7 @@ func TestInterfaceSliceSave(t *testing.T) {
                B: "foo_save",
        }
 
-       i := []interface{}{&tr}
+       i := []interface{}{tr}
 
        err = db.Save("test", &i)
        if err != nil {
```

* Let's teach the library to accept non-pointer structs for Save, Update, Insert:

```
diff --git a/query_test.go b/query_test.go
index ea4b7dc..ded7318 100644
--- a/query_test.go
+++ b/query_test.go
@@ -223,8 +223,8 @@ func TestInsertStruct(t *testing.T) {
 
        tr := testRow{B: "foo3"}
        err := db.Insert("test", tr)
-       if err == nil {
-               t.Error("Insert must not accept struct.")
+       if err != nil {
+               t.Error(err)
        }
 }
```

* Also accept non-pointer slices for InsertBulk

**Comment by DigitalPhilosopher** [comment] 2019-11-02 09:29
The PR #3 would resolve this problem. However I would suggest to not implement this functionality and concentrate on one problem. With this functionality, the functions INSERT/UPDATE/SAVE... implement two responsibilities:

- Perform the actual query (this is the goal)
- Make sure to check the user input and handle it correct

 The second responsibility makes it simpler for the caller, but the actual functionality is now overloaded with extensive responsibility. This would need to be checked in every new functionality and result in a lot of duplicate code. The code would get unreadable and not maintainable. Furthermore it is possible that further developers add bugs (not intentionally), because they forgot to check all the possible ways to pass data.

I would suggest that the functions INSERT/UPDATE/... should focus on their main responsibility and constrain the user to use one format.

**Comment by martinrode** [comment] 2019-11-04 08:30
> The second responsibility makes it simpler for the caller, but the actual functionality is now overloaded with extensive responsibility. This would need to be checked in every new functionality and result in a lot of duplicate code.

The patch actually does less checks, so I am not sure if I can follow you here.

The bigger problem is may be that setting the primary key after INSERT does not work if the record isn't passed as a pointer.

**Comment by DigitalPhilosopher** [comment] 2019-11-04 10:49
After moving the check out of setPrimaryKey, there are now two checks, since the function is called twice in the code. Also adding another call to it would result in yet another check, which the caller needs to do.

Yes, this problem results in unexpected behavior. Therefore I would not recommend accepting both, Pointers and non Pointers.
To address this problem, we could actually return the data, including the new key.

**Closed** 2020-01-29 08:08 UTC
